spring.application.name=xmlDocument
server.port = 9000

# NIBSS Configuration
nibss.private.key.path=C:\\Users\\semicolon\\Downloads\\xmlDocument\\xmlDocument\\banks_private.pem
nibss.public.key.path=C:\\Users\\semicolon\\Downloads\\xmlDocument\\xmlDocument\\banks_public.pem
nibss.api.url=https://nps-test.nibss-plc.com.ng:8022/nps/acmt/023


institution.id=999999
creator.name=jhfcvbnm  nm