package com.strata.xmlDocument.infrastructure.adapter.output.utils;

public final class XmlTemplate {

    private XmlTemplate() {
        // Utility class
    }

    private static final String TEMPLATE = "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?> " +
            "<ns2:Document xmlns:ns2=\"urn:iso:std:iso:20022:tech:xsd:acmt.023.001.04\"> " +
            "<IdVrfctnReq> " +
            "<Assgnmt> " +
            "<!-- Unique message reference as generated by sending party. --> " +
            "<MsgId>%s</MsgId> " +
            "<!-- Mandatory Field --> " +
            "<!-- Document creation local date-time --> " +
            "<CreDtTm>%s</CreDtTm> " +
            "<!-- Mandatory Field --> " +
            "<Cretr> " +
            "<Pty> " +
            "<Nm>%s</Nm> " +
            "<!-- Mandatory Field --> " +
            "</Pty> " +
            "</Cretr> " +
            "<Assgnr> " +
            "<Pty> " +
            "<Nm>%s</Nm> " +
            "<!-- Mandatory Field --> " +
            "</Pty> " +
            "<Agt> " +
            "<FinInstnId> " +
            "<BICFI>%s</BICFI> " +
            "<!-- Optional Field --> " +
            "<ClrSysMmbId> " +
            "<MmbId>%s</MmbId> " +
            "<!-- Mandatory Field --> " +
            "</ClrSysMmbId> " +
            "</FinInstnId> " +
            "</Agt> " +
            "</Assgnr> " +
            "<Assgne> " +
            "<Agt> " +
            "<FinInstnId> " +
            "<BICFI>%s</BICFI> " +
            "<!-- Optional Field --> " +
            "<ClrSysMmbId> " +
            "<MmbId>%s</MmbId> " +
            "<!-- Mandatory Field --> " +
            "</ClrSysMmbId> " +
            "</FinInstnId> " +
            "</Agt> " +
            "</Assgne> " +
            "</Assgnmt> " +
            "<SensitiveData> " +
            "<Vrfctn> " +
            "<Id>%s</Id> " +
            "<!-- Mandatory Field --> " +
            "<PtyAndAcctId> " +
            "<Pty> " +
            "<Nm>%s</Nm> " +
            "<!-- Mandatory Field --> " +
            "</Pty> " +
            "<Acct> " +
            "<Id> " +
            "<IBAN>%s</IBAN> " +
            "<!-- Mandatory Field --> " +
            "</Id> " +
            "</Acct> " +
            "</PtyAndAcctId> " +
            "</Vrfctn> " +
            "</SensitiveData> " +
            "</IdVrfctnReq> " +
            "</ns2:Document>";

    public static String generateXml(String msgId, String creDtTm, String sendingPartyName,
                                     String sourceId, String beneficiaryId, String partyToVerifyName, String accountNumber) {
        return String.format(TEMPLATE, msgId, creDtTm, sendingPartyName, sendingPartyName,
                             sourceId, sourceId, beneficiaryId, beneficiaryId, msgId, partyToVerifyName, accountNumber);
    }
}